apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sms-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/biswajit134/GitOps-School-Management-System.git
    targetRevision: main
    path: app-helm/sms-frontend
    helm:
      releaseName: sms-frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
  destination:
    server: https://kubernetes.default.svc
    namespace: sms-app